### ISSUE TITLE
Browser.search_engine?(%Plug.Conn{}) fails

### ISSUE THREAD

**Issue by the-guitarman** [tuvistavie/elixir-browser#15]
Hi, I checked out your package to detect bots and search engines. 

At first I tested for bots: 
```
iex> Browser.bot?(%Plug.Conn{})
false
```
Ist returned false like I expected, because it's an empty struct.

Then I tried to detect search engines and got an error:
```
iex> Browser.search_engine?(%Plug.Conn{})
** (FunctionClauseError) no function clause matching in String.contains?/2    
    
    The following arguments were given to String.contains?/2:
     
        # 1
        %Plug.Conn{
          adapter: {Plug.MissingAdapter, :...},
          assigns: %{},
          before_send: [],
          body_params: %Plug.Conn.Unfetched{aspect: :body_params},
          cookies: %Plug.Conn.Unfetched{aspect: :cookies},
          halted: false,
          host: "www.example.com",
          method: "GET",
          owner: nil,
          params: %Plug.Conn.Unfetched{aspect: :params},
          path_info: [],
          path_params: %{},
          peer: nil,
          port: 0,
          private: %{},
          query_params: %Plug.Conn.Unfetched{aspect: :query_params},
          query_string: "",
          remote_ip: nil,
          req_cookies: %Plug.Conn.Unfetched{aspect: :cookies},
          req_headers: [],
          request_path: "",
          resp_body: nil,
          resp_cookies: %{},
          resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}],
          scheme: :http,
          script_name: [],
          secret_key_base: nil,
          state: :unset,
          status: nil
        }
    
        # 2
        "Baidu"
    
    Attempted function clauses (showing 3 out of 3):
    
        def contains?(string, []) when is_binary(string)
        def contains?(string, contents) when is_binary(string) and is_list(contents)
        def contains?(string, contents) when is_binary(string)
    
    (elixir) lib/string.ex:2009: String.contains?/2
    (elixir) lib/enum.ex:2838: Enum.any_list/2
```

The same happened in my real app at dev mode.
May be this could be interesting for you.

**Comment by danhper** [comment]
This should now be fixed thanks to your PR.
